services:
  app:
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "8888:8888" 
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "-m", "melo.app", "--host", "0.0.0.0", "--port", "8888"]
